# This is a basic workflow to help you get started with Actions

name: MyGithubWebsite

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
          dotnet-version: 5.x
          
      - name: Publish .Net Core Project
        run: dotnet publish BlazorWASM/BlazorWASM.csproj -c Release -o release --nologo

      - name: Deploy to GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: JamesIves/github-pages-deploy-action@132898c54c57c7cc6b80eb3a89968de8fc283505
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          # In order for GitHub to trigger the rebuild of your page you must provide the action with the repositories provided GitHub token.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This is the branch you wish to deploy to, for example gh-pages or docs.
          BRANCH: gh-pages
          # The folder in your repository that you want to deploy. If your build script compiles into a directory named build you would put it here. Folder paths cannot have a leading / or ./. If you wish to deploy the root directory you can place a . here.
          FOLDER: release/wwwroot
